### ISSUE TITLE
Update needed for Rails 6.1

### ISSUE THREAD

**Issue by swrobel** [falconed/pgreset#2]
It seems the method of accessing db config has changed: https://github.com/rails/rails/commit/4ee9dab316296ee96629f2bffbab756a163d1b49

Current behavior with 6.1:
```
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fb245d69238>
Did you mean?  configuration_hash
gems/pgreset-0.1.1/lib/pgreset.rb:14:in `drop'
```

**Comment by dafalcon** [comment]
Thank you @ekampp and @layerssss for your help with this!  The changes looked good to me so I merged them and pushed v0.2 to rubygems along with some minor housekeeping changes.  Let me know if you run into any other issues.

**Comment by swrobel** [comment]
Thank you @dafalcon @ekampp & @layerssss!!!

@dafalcon would you mind tagging the release?

**Comment by dafalcon** [comment]
> @dafalcon would you mind tagging the release?

Done, thanks for the reminder!

**Comment by katelovescode** [comment]
When I try to reset the db on Rails 6.1.1 and pgreset 0.2, I get this stack trace:
```
# ActiveRecord Tasks PostgreSQLDatabaseTasks is hitting the rescue because of the NoMethodError below
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007f8f358cc4b0>
Did you mean?  configuration_hash
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/pgreset-0.2/lib/pgreset.rb:13:in `rescue in drop'

Caused by:
NoMethodError: private method `configuration_hash' called for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007f8f358cc4b0>
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/pgreset-0.2/lib/pgreset.rb:11:in `drop'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:199:in `drop'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:214:in `block in drop_current'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:506:in `block (2 levels) in each_current_configuration'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:503:in `each'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:503:in `block in each_current_configuration'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:502:in `each'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:502:in `each_current_configuration'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:214:in `drop_current'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/activerecord-6.1.1/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <main>'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/katedonaldson/.rvm/gems/ruby-2.6.6@pieforproviders/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
```

**Comment by layerssss** [comment]
@katelovescode Weird, it doesn't seem I can reproduce this, can you check if I'm missing anything in my versions? (don't forget to `spring stop` when changing gem versions)

```
{14:37}~/fms/fms_rails:michael/rails-611 ✗ ➭ bundle info rails
  * rails (6.1.1)
        Summary: Full-stack web application framework.
        Homepage: https://rubyonrails.org
        Path: /Users/layerssss/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails-6.1.1
{14:37}~/fms/fms_rails:michael/rails-611 ✗ ➭ bundle info pgreset
  * pgreset (0.2)
        Summary: Automatically kill postgres connections during db:reset
        Homepage: https://github.com/dafalcon/pgreset
        Path: /Users/layerssss/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/pgreset-0.2
{14:37}~/fms/fms_rails:michael/rails-611 ✗ ➭ bundle info pg
  * pg (1.2.3)
        Summary: Pg is the Ruby interface to the {PostgreSQL RDBMS}[http://www.postgresql.org/]
        Homepage: https://github.com/ged/ruby-pg
        Path: /Users/layerssss/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/pg-1.2.3
```

**Comment by katelovescode** [comment]
Full stack trace:
```
$ be rails db:reset --trace
** Invoke db:reset (first_time)
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:drop
** Invoke db:drop:_unsafe (first_time)
** Invoke db:load_config 
** Execute db:drop:_unsafe
undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fd127247570>
Did you mean?  configuration_hash
Couldn't drop database 'pie_development'
rails aborted!
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fd127247570>
Did you mean?  configuration_hash
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/pgreset-0.2/lib/pgreset.rb:13:in `rescue in drop'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/pgreset-0.2/lib/pgreset.rb:10:in `drop'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:199:in `drop'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:214:in `block in drop_current'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:506:in `block (2 levels) in each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:503:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:503:in `block in each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:502:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:502:in `each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:214:in `drop_current'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/railties/databases.rake:64:in `block (2 levels) in <main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/command.rb:52:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands.rb:18:in `<main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
/Users/user/Projects/project/bin/rails:10:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/user/Projects/project/bin/spring:15:in `require'
/Users/user/Projects/project/bin/spring:15:in `<top (required)>'
bin/rails:4:in `load'
bin/rails:4:in `<main>'

Caused by:
NoMethodError: private method `configuration_hash' called for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fd127247570>
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/pgreset-0.2/lib/pgreset.rb:11:in `drop'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:199:in `drop'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:214:in `block in drop_current'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:506:in `block (2 levels) in each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:503:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:503:in `block in each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:502:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:502:in `each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:214:in `drop_current'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/railties/databases.rake:64:in `block (2 levels) in <main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/command.rb:52:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands.rb:18:in `<main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
/Users/user/Projects/project/bin/rails:10:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/user/Projects/project/bin/spring:15:in `require'
/Users/user/Projects/project/bin/spring:15:in `<top (required)>'
bin/rails:4:in `load'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe
```
I did `spring stop` when I tested yesterday and again today, and still got the same error.  Here are my versions:

```
$ bundle info rails
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
  * rails (6.1.1)
        Summary: Full-stack web application framework.
        Homepage: https://rubyonrails.org
        Path: /Users/user/.rvm/gems/ruby-2.6.6@project/gems/rails-6.1.1
$ bundle info pgreset
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
  * pgreset (0.2)
        Summary: Automatically kill postgres connections during db:reset
        Homepage: https://github.com/dafalcon/pgreset
        Path: /Users/user/.rvm/gems/ruby-2.6.6@project/gems/pgreset-0.2
$ bundle info pg
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
  * pg (1.2.3)
        Summary: Pg is the Ruby interface to the {PostgreSQL RDBMS}[http://www.postgresql.org/]
        Homepage: https://github.com/ged/ruby-pg
        Path: /Users/user/.rvm/gems/ruby-2.6.6@project/gems/pg-1.2.3
```

I've also tried completely resetting my gemset, and I've tried with rails 6.1.0 as well as 6.1.1 :( [the PR](https://github.com/dafalcon/pgreset/pull/5) I submitted was the only way I got it working locally, by removing `self.` in the gem as installed in my rvm gemset. 😢

**Comment by layerssss** [comment]
@katelovescode Finally got this, it was the ruby version. Prior to ruby 2.7, calling private method with `self` (unless write/assign) results in this error. https://blog.saeloun.com/2019/12/24/ruby-2-7-allows-calling-a-private-method-with-self.html

I'll add some changes to your pull-request to address that.

**Comment by katelovescode** [comment]
Amazing!  Thank you!
